#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable --now 2ping || true
systemctl enable --now arpalert || true
systemctl enable --now arpwatch || true
systemctl enable --now avahi-daemon || true
systemctl enable --now bacula-fd || true
systemctl enable bacula-sd || true
systemctl enable --now bettercap || true
systemctl enable --now bluetooth || true
systemctl enable --now blueman-mechanism || true
systemctl enable --now btrbk.timer || true
systemctl enable --now btrbk.service || true
systemctl enable --now btrfs-balance.service || true
systemctl enable --now btrfs-balance.timer || true
systemctl enable --now btrfs-defrag.service || true
systemctl enable --now btrfs-defrag.timer || true
systemctl enable --now btrfsmaintenance-refresh.path || true
systemctl enable --now btrfsmaintenance-refresh.service || true
systemctl enable --now btrfs-scrub.timer || true
systemctl enable --now btrfs-scrub.service || true
systemctl enable --now btrfs-trim.timer || true
systemctl enable --now btrfs-trim.service || true
systemctl enable --now ceph-fuse.target || true
systemctl enable --now clamav-daemon || true
systemctl enable --now clamav-freshclam || true
systemctl enable --now clamav-milter || true
systemctl enable --now containerd || true
systemctl enable --now cups-browsed || true
systemctl enable --now cups || true
systemctl enable --now cups.path || true
systemctl enable --now cups.socket || true
systemctl unmask darkstat || true
systemctl enable --now darkstat || true
systemctl enable --now docker || true
systemctl enable --now docker.socket || true
systemctl enable --now e2scrub_reap || true
systemctl enable --now e2scrub_all.timer || true
systemctl enable --now etc-setserial || true
systemctl enable --now iptables || true
systemctl enable --now ip6tables || true
systemctl enable --now netfilter-persistent || true
systemctl enable --now nftables || true
systemctl enable --now gns3-server || true
systemctl enable --now hddtemp || true
systemctl unmask hostapd || true
systemctl enable hostapd || true
systemctl enable --now libvirtd.service || true
systemctl enable --now virtlockd.socket || true
systemctl enable --now virtlogd.socket || true
systemctl enable --now libvirtd.socket || true
systemctl enable --now libvirtd-ro.socket || true
systemctl enable --now libvirt-guests.service || true
systemctl enable --now libvirtd-admin.socket || true
systemctl enable --now virtlockd-admin.socket || true
systemctl enable --now virtlogd-admin.socket || true
systemctl enable --now spice-vdagentd.service || true
systemctl enable --now spice-vdagentd.socket || true
systemctl enable --now spice-webdavd.service || true
systemctl enable --now lm-sensors || true
systemctl enable --now lxcfs || true
systemctl enable --now lxc-net || true
systemctl enable --now lxc || true
systemctl enable --now mlocate.timer || true
systemctl enable --now mlocate.service || true
systemctl enable --now neo4j || true
systemctl enable --now nfs-client.target || true
systemctl enable --now nfs-kernel-server || true
systemctl enable --now nfs-blkmap || true
systemctl enable --now nfs-server || true
systemctl enable --now portmap || true
systemctl enable --now rpcbind || true
systemctl enable --now rpcbind.socket || true
systemctl enable --now ntp || true
systemctl enable --now ntpd || true
systemctl enable --now ntpsec || true
systemctl enable --now ntpsec-rotate-stats || true
systemctl enable --now ntpsec-rotate-stats.timer || true
systemctl enable --now ntpsec-systemd-netif || true
systemctl enable --now ntpsec-systemd-netif.path || true
systemctl enable --now ntpsec-wait || true
systemctl enable --now o2cb || true
systemctl enable --now ocfs2 || true
systemctl enable --now openvpn || true
systemctl enable --now rpcbind || true
systemctl enable --now rpcbind.socket || true
systemctl enable --now rsync || true
systemctl enable --now setserial || true
systemctl enable --now smartmontools || true
systemctl enable --now snapper-boot.timer || true
systemctl enable --now snapper-boot.service || true
systemctl enable --now snapper-cleanup.timer || true
systemctl enable --now snapper-cleanup.service || true
systemctl enable --now snapperd || true
systemctl enable --now snapper-timeline.timer || true
systemctl enable --now snapper-timeline.service || true
systemctl enable --now ssh || true
systemctl enable --now sysstat || true
systemctl enable vboxweb || true
systemctl enable virtualbox || true
systemctl enable --now virtualbox-guest-utils || true
systemctl enable --now vgauth || true
systemctl enable --now open-vm-tools || true
systemctl enable zfs-fuse || true
systemctl enable --now podman || true
systemctl enable --now podman-auto-update || true
systemctl enable --now podman.socket || true
systemctl enable --now nmbd || true
systemctl enable --now smbd || true
systemctl enable --now puppet || true
systemctl enable --now pxp-agent || true
