#!/bin/bash

set -e

sudo systemctl disable anydesk
sudo systemctl stop anydesk
sudo systemctl disable arpwatch
sudo systemctl stop arpwatch
sudo systemctl disable avahi-daemon
sudo systemctl stop avahi-daemon
sudo systemctl disable avahi-daemon.socket
sudo systemctl stop avahi-daemon.socket
sudo systemctl disable bacula-fd
sudo systemctl stop bacula-fd
sudo systemctl disable bacula-sd
sudo systemctl stop bacula-sd
sudo systemctl disable clamav-daemon
sudo systemctl stop clamav-daemon
sudo systemctl disable bettercap
sudo systemctl stop bettercap
sudo systemctl disable blueman-mechanism
sudo systemctl stop blueman-mechanism
sudo systemctl disable bluetooth
sudo systemctl stop bluetooth
sudo systemctl disable ceph-fuse.target
sudo systemctl stop ceph-fuse.target
sudo systemctl disable clamav-freshclam
sudo systemctl stop clamav-freshclam
sudo systemctl disable cups-browsed
sudo systemctl stop cups-browsed
sudo systemctl disable cups
sudo systemctl stop cups
sudo systemctl disable docker
sudo systemctl stop docker
sudo systemctl disable docker.socket
sudo systemctl stop docker.socket
sudo systemctl disable e2scrub_all.timer
sudo systemctl stop e2scrub_all.timer
sudo systemctl disable e2scrub_reap
sudo systemctl stop e2scrub_reap
sudo systemctl disable etc-setserial
sudo systemctl stop etc-setserial
sudo systemctl disable gns3-server
sudo systemctl stop gns3-server
sudo systemctl disable hostapd
sudo systemctl stop hostapd
sudo systemctl disable ip6tables
sudo systemctl stop ip6tables
sudo systemctl disable iptables
sudo systemctl stop iptables
sudo systemctl disable irqbalance
sudo systemctl stop irqbalance
sudo systemctl disable libvirtd.service
sudo systemctl stop libvirtd.service
sudo systemctl disable virtlockd.socket
sudo systemctl stop virtlockd.socket
sudo systemctl disable virtlogd.socket
sudo systemctl stop virtlogd.socket
sudo systemctl disable libvirtd.socket
sudo systemctl stop libvirtd.socket
sudo systemctl disable libvirtd-ro.socket
sudo systemctl stop libvirtd-ro.socket
sudo systemctl disable libvirt-guests.service
sudo systemctl stop libvirt-guests.service
sudo systemctl disable libvirtd-admin.socket
sudo systemctl stop libvirtd-admin.socket
sudo systemctl disable virtlockd-admin.socket
sudo systemctl stop virtlockd-admin.socket
sudo systemctl disable virtlogd-admin.socket
sudo systemctl stop virtlogd-admin.socket
sudo systemctl disable lm-sensors
sudo systemctl stop lm-sensors
sudo systemctl disable lockdown
sudo systemctl stop lockdown
sudo systemctl disable lxcfs
sudo systemctl stop lxcfs
sudo systemctl disable lxc-net
sudo systemctl stop lxc-net
sudo systemctl disable lxc
sudo systemctl stop lxc
sudo systemctl disable neo4j
sudo systemctl stop neo4j
sudo systemctl disable netfilter-persistent
sudo systemctl stop netfilter-persistent
sudo systemctl disable nfs-client.target
sudo systemctl stop nfs-client.target
sudo systemctl disable nfs-kernel-server
sudo systemctl stop nfs-kernel-server
sudo systemctl disable nfs-server
sudo systemctl stop nfs-server
sudo systemctl disable ntp
sudo systemctl stop ntp
sudo systemctl disable o2cb
sudo systemctl stop o2cb
sudo systemctl disable ocfs2
sudo systemctl stop ocfs2
sudo systemctl disable open-vm-tools
sudo systemctl stop open-vm-tools
sudo systemctl disable openvpn
sudo systemctl stop openvpn
sudo systemctl disable portmap
sudo systemctl stop portmap
sudo systemctl disable rpcbind
sudo systemctl stop rpcbind
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.socket
sudo systemctl disable rsync
sudo systemctl stop rsync
sudo systemctl disable setserial
sudo systemctl stop setserial
sudo systemctl disable ssh
sudo systemctl stop ssh
sudo systemctl disable sysstat
sudo systemctl stop sysstat
sudo systemctl disable smartmontools
sudo systemctl stop smartmontools
sudo systemctl disable teamviewerd
sudo systemctl stop teamviewerd
sudo systemctl disable vboxweb
sudo systemctl stop vboxweb
sudo systemctl disable virtualbox-guest-utils
sudo systemctl stop virtualbox-guest-utils
sudo systemctl disable zfs-fuse
sudo systemctl stop zfs-fuse
