#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command to continue."
        exit 1
fi

systemctl enable --now 2ping || true
systemctl enable --now arpalert || true
systemctl enable --now arpwatch || true
systemctl enable --now avahi-daemon.socket || true
systemctl enable --now avahi-daemon.service || true
systemctl enable --now bacula-fd || true
systemctl enable --now bacula-sd || true
systemctl enable --now bettercap || true
systemctl enable --now blueman-mechanism || true
systemctl enable --now bluetooth || true
systemctl enable --now btrbk.service || true
systemctl enable --now btrbk.timer || true
systemctl enable --now btrfs-balance.service || true
systemctl enable --now btrfs-balance.timer || true
systemctl enable --now btrfs-defrag.service || true
systemctl enable --now btrfs-defrag.timer || true
systemctl enable --now btrfsmaintenance-refresh.path || true
systemctl enable --now btrfsmaintenance-refresh.service || true
systemctl enable --now btrfs-scrub.service || true
systemctl enable --now btrfs-scrub.timer || true
systemctl enable --now btrfs-trim.service || true
systemctl enable --now btrfs-trim.timer || true
systemctl enable --now ceph-fuse.target || true
systemctl enable --now chrony || true
systemctl enable --now clamav-daemon.socket || true
systemctl enable --now clamav-daemon.service || true
systemctl enable --now clamav-freshclam || true
systemctl enable --now clamav-milter || true
systemctl enable --now containerd || true
systemctl enable --now cups-browsed || true
systemctl enable --now cups.path || true
systemctl enable --now cups.socket || true
systemctl enable --now cups.service || true
systemctl enable --now darkstat || true
systemctl enable --now docker.socket || true
systemctl enable --now docker.service || true
systemctl enable --now e2scrub_all.timer || true
systemctl enable --now e2scrub_reap || true
systemctl enable --now etc-setserial || true
systemctl enable --now fio || true
systemctl enable --now gns3-server || true
systemctl enable --now hddtemp || true
systemctl enable --now ip6tables || true
systemctl enable --now iptables || true
systemctl enable --now libvirtd.service || true
systemctl enable --now libvirt-guests.service || true
systemctl enable --now lm-sensors || true
systemctl enable --now lxcfs || true
systemctl enable --now lxc-monitord.service || true
systemctl enable --now lxc-net || true
systemctl enable --now lxc || true
systemctl enable --now lxd-agent.service || true
systemctl enable --now lxd.socket || true
systemctl enable --now lxd.service || true
systemctl enable --now lxd-containers.service || true
systemctl enable --now neo4j || true
systemctl enable --now netfilter-persistent || true
systemctl enable --now nfs-blkmap.service || true
systemctl enable --now nfs-client.target || true
systemctl enable --now nfs-common.service || true
systemctl enable --now nfsdcld.service || true
systemctl enable --now nfs-idmapd.service || true
systemctl enable --now nfs-kernel-server || true
systemctl enable --now nfs-mountd.service || true
systemctl enable --now nfs-server.service || true
systemctl enable --now nfs-utils.service || true
systemctl enable --now nftables || true
systemctl enable --now nmbd || true
systemctl enable --now o2cb || true
systemctl enable --now ocfs2 || true
systemctl enable --now openvpn || true
systemctl enable --now plocate-updatedb.service || true
systemctl enable --now plocate-updatedb.timer || true
systemctl enable --now podman-auto-update.service || true
systemctl enable --now podman-auto-update.timer || true
systemctl enable --now podman-restart.service || true
systemctl enable --now podman.socket || true
systemctl enable --now podman.service || true
systemctl enable --now portmap || true
systemctl enable --now puppet || true
systemctl enable --now pxp-agent || true
systemctl enable --now rpcbind.socket || true
systemctl enable --now rpcbind.service || true
systemctl enable --now rpc-gssd.service || true
systemctl enable --now rpc-statd-notify.service || true
systemctl enable --now rpc-statd.service || true
systemctl enable --now rpc-svcgssd.service || true
systemctl enable --now rsync || true
systemctl enable --now samba-ad-dc.service || true
systemctl enable --now setserial || true
systemctl enable --now smartmontools || true
systemctl enable --now smbd || true
systemctl enable --now snapper-boot.service || true
systemctl enable --now snapper-boot.timer || true
systemctl enable --now snapper-cleanup.service || true
systemctl enable --now snapper-cleanup.timer || true
systemctl enable --now snapperd || true
systemctl enable --now snapper-timeline.service || true
systemctl enable --now snapper-timeline.timer || true
systemctl enable --now ssh.socket || true
systemctl enable --now ssh.service || true
systemctl enable --now sysstat-collect.service || true
systemctl enable --now sysstat-collect.timer || true
systemctl enable --now sysstat || true
systemctl enable --now sysstat-summary.service || true
systemctl enable --now sysstat-summary.timer || true
systemctl enable tftpd-hpa || true
systemctl start tftpd-hpa || true
systemctl enable --now vault || true
systemctl enable --now virtlockd-admin.socket || true
systemctl enable --now virtlockd.socket || true
systemctl enable --now virtlockd.service || true
systemctl enable --now virtlogd-admin.socket || true
systemctl enable --now virtlogd.socket || true
systemctl enable --now virtlogd.service || true
systemctl enable --now zfs-fuse || true
