#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable avahi-daemon || true
systemctl stop avahi-daemon || true
systemctl disable avahi-daemon.socket || true
systemctl stop avahi-daemon.socket || true
