#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable avahi-daemon
systemctl start avahi-daemon
systemctl enable avahi-daemon.socket
systemctl start avahi-daemon.socket
