#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable bacula-fd || true
systemctl stop bacula-fd || true
systemctl disable bacula-sd || true
systemctl stop bacula-sd || true
