#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable bluetooth
systemctl stop bluetooth
systemctl disable blueman-mechanism
systemctl stop blueman-mechanism
