#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable bluetooth || true
systemctl start bluetooth || true
systemctl enable blueman-mechanism || true
systemctl start blueman-mechanism || true
