#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable btrbk.timer || true
systemctl start btrbk.timer || true
systemctl enable btrbk.service || true
systemctl start btrbk.service || true
