#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable btrfs-trim.timer || true
systemctl start btrfs-trim.timer || true
systemctl enable btrfs-trim.service || true
systemctl start btrfs-trim.service || true
