#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable btrfs-trim.timer || true
systemctl stop btrfs-trim.timer || true
systemctl disable btrfs-trim.service || true
systemctl stop btrfs-trim.service || true
