#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable btrfsmaintenance-refresh.path || true
systemctl stop btrfsmaintenance-refresh.path || true
systemctl disable btrfsmaintenance-refresh.service || true
systemctl stop btrfsmaintenance-refresh.service || true
