#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command."
        exit 1
fi

systemctl disable --now ceph-fuse.target || true
