#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable clamav-daemon || true
systemctl start clamav-daemon || true
systemctl enable clamav-freshclam || true
systemctl start clamav-freshclam || true
systemctl enable clamav-milter || true
systemctl start clamav-milter || true
