#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable clamav-daemon
systemctl start clamav-daemon
systemctl enable clamav-freshclam
systemctl start clamav-freshclam
systemctl enable clamav-milter
systemctl start clamav-milter
