#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command to continue."
        exit 1
fi

systemctl enable --now clamav-daemon.socket || true
systemctl enable --now clamav-daemon.service || true
systemctl enable --now clamav-freshclam || true
systemctl enable --now clamav-milter || true
