#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable clamav-daemon
systemctl stop clamav-daemon
systemctl disable clamav-freshclam
systemctl stop clamav-freshclam
systemctl disable clamav-milter
systemctl stop clamav-milter

