#!/bin/bash

set -e

sudo systemctl disable clamav-daemon
sudo systemctl stop clamav-daemon
sudo systemctl disable clamav-freshclam
sudo systemctl stop clamav-freshclam
sudo systemctl disable clamav-milter
sudo systemctl stop clamav-milter

