#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable cups
systemctl stop cups
systemctl disable cups.path
systemctl stop cups.path
systemctl disable cups.socket
systemctl stop cups.socket
systemctl disable cups-browsed
systemctl stop cups-browsed
