#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command to continue."
        exit 1
fi

systemctl disable --now cups || true
systemctl disable --now cups.path || true
systemctl disable --now cups.socket || true
systemctl disable --now cups-browsed || true
