#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command."
        exit 1
fi

systemctl enable --now cups || true
systemctl enable --now cups.path || true
systemctl enable --now cups.socket || true
systemctl enable --now cups-browsed || true
