#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable docker || true
systemctl stop docker || true
systemctl disable docker.socket || true
systemctl stop docker.socket || true
systemctl disable containerd || true
systemctl stop containerd || true
