#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable e2scrub_reap || true
systemctl stop e2scrub_reap || true
systemctl disable e2scrub_all.timer || true
systemctl stop e2scrub_all.timer || true
