#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command to continue."
        exit 1
fi

systemctl enable --now e2scrub_all.service || true
systemctl enable --now e2scrub_all.timer || true
systemctl enable --now e2scrub_reap || true
