#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable iptables || true
systemctl stop iptables || true
systemctl disable ip6tables || true
systemctl stop ip6tables || true
systemctl disable netfilter-persistent || true
systemctl stop netfilter-persistent || true
