#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command to continue."
        exit 1
fi

systemctl enable --now iptables || true
systemctl enable --now ip6tables || true
systemctl enable --now netfilter-persistent || true
systemctl enable --now nftables || true
