#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable iptables || true
systemctl start iptables || true
systemctl enable ip6tables || true
systemctl start ip6tables || true
systemctl enable netfilter-persistent || true
systemctl start netfilter-persistent || true
