#!/bin/bash

set -e

sudo systemctl enable iptables
sudo systemctl start iptables
sudo systemctl enable ip6tables
sudo systemctl start ip6tables
sudo systemctl enable netfilter-persistent
sudo systemctl start netfilter-persistent
