#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable libvirtd.service
systemctl start libvirtd.service
systemctl enable virtlockd.socket
systemctl start virtlockd.socket
systemctl enable virtlogd.socket
systemctl start virtlogd.socket
systemctl enable libvirtd.socket
systemctl start libvirtd.socket
systemctl enable libvirtd-ro.socket
systemctl start libvirtd-ro.socket
systemctl enable libvirt-guests.service
systemctl start libvirt-guests.service
systemctl enable libvirtd-admin.socket
systemctl start libvirtd-admin.socket
systemctl enable virtlockd-admin.socket
systemctl start virtlockd-admin.socket
systemctl enable virtlogd-admin.socket
systemctl start virtlogd-admin.socket
