#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable libvirtd.service
systemctl stop libvirtd.service
systemctl disable virtlockd.socket
systemctl stop virtlockd.socket
systemctl disable virtlogd.socket
systemctl stop virtlogd.socket
systemctl disable libvirtd.socket
systemctl stop libvirtd.socket
systemctl disable libvirtd-ro.socket
systemctl stop libvirtd-ro.socket
systemctl disable libvirt-guests.service
systemctl stop libvirt-guests.service
systemctl disable libvirtd-admin.socket
systemctl stop libvirtd-admin.socket
systemctl disable virtlockd-admin.socket
systemctl stop virtlockd-admin.socket
systemctl disable virtlogd-admin.socket
systemctl stop virtlogd-admin.socket
