#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable --now libvirtd.service || true
systemctl enable --now virtlockd.socket || true
systemctl enable --now virtlogd.socket || true
systemctl enable --now libvirtd.socket || true
systemctl enable --now libvirtd-ro.socket || true
systemctl enable --now libvirt-guests.service || true
systemctl enable --now libvirtd-admin.socket || true
systemctl enable --now virtlockd-admin.socket || true
systemctl enable --now virtlogd-admin.socket || true
