sudo systemctl enable libvirtd.service
sudo systemctl start libvirtd.service
sudo systemctl enable virtlockd.socket
sudo systemctl start virtlockd.socket
sudo systemctl enable virtlogd.socket
sudo systemctl start virtlogd.socket
sudo systemctl enable libvirtd.socket
sudo systemctl start libvirtd.socket
sudo systemctl enable libvirtd-ro.socket
sudo systemctl start libvirtd-ro.socket
sudo systemctl enable libvirt-guests.service
sudo systemctl start libvirt-guests.service
sudo systemctl enable libvirtd-admin.socket
sudo systemctl start libvirtd-admin.socket
sudo systemctl enable virtlockd-admin.socket
sudo systemctl start virtlockd-admin.socket
sudo systemctl enable virtlogd-admin.socket
sudo systemctl start virtlogd-admin.socket
