#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable lxcfs
systemctl start lxcfs
systemctl enable lxc-net
systemctl start lxc-net
systemctl enable lxc
systemctl start lxc
