#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable lxcfs || true
systemctl stop lxcfs || true
systemctl disable lxc-net || true
systemctl stop lxc-net || true
systemctl disable lxc || true
systemctl stop lxc || true
