#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable mlocate.timer || true
systemctl start mlocate.timer || true
systemctl enable mlocate.service || true
systemctl start mlocate.service || true
