sudo systemctl disable nfs-client
sudo systemctl stop nfs-client
sudo systemctl disable nfs-kernel-server
sudo systemctl stop nfs-kernel-server
sudo systemctl disable nfs-server
sudo systemctl stop nfs-server
sudo systemctl disable portmap
sudo systemctl stop portmap
sudo systemctl disable rpcbind
sudo systemctl stop rpcbind
sudo systemctl disable rpcbind.socket
sudo systemctl stop rpcbind.socket
