#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable nfs-client.target || true
systemctl stop nfs-client.target || true
systemctl disable nfs-kernel-server || true
systemctl stop nfs-kernel-server || true
systemctl disable nfs-server || true
systemctl stop nfs-server || true
systemctl disable portmap || true
systemctl stop portmap || true
systemctl disable rpcbind || true
systemctl stop rpcbind || true
systemctl disable rpcbind.socket || true
systemctl stop rpcbind.socket || true
