#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable podman || true
systemctl stop podman || true
systemctl disable podman-auto-update || true
systemctl stop podman-auto-update || true
systemctl disable podman.socket || true
systemctl stop podman.socket || true
