#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable podman || true
systemctl start podman || true
systemctl enable podman-auto-update || true
systemctl start podman-auto-update || true
systemctl enable podman.socket || true
systemctl start podman.socket || true
