#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable --now podman || true
systemctl enable --now podman-auto-update || true
systemctl enable --now podman.socket || true
