#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command to continue."
        exit 1
fi

systemctl disable --now podman || true
systemctl disable --now podman-auto-update || true
systemctl disable --now podman.socket || true
