#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command to continue."
        exit 1
fi

systemctl enable --now podman.service || true
systemctl enable --now podman.socket || true
systemctl enable --now podman-restart.service || true
systemctl enable --now podman-auto-update.service || true
systemctl enable --now podman-auto-update.timer || true
