#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable snapper-cleanup.timer || true
systemctl start snapper-cleanup.timer || true
systemctl enable snapper-cleanup.service || true
systemctl start snapper-cleanup.service || true
