#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl disable snapper-boot.timer || true
systemctl stop snapper-boot.timer || true
systemctl disable snapper-boot.service || true
systemctl stop snapper-boot.service || true
