#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable spice-vdagentd.service || true
systemctl start spice-vdagentd.service || true
systemctl enable spice-vdagentd.socket || true
systemctl start spice-vdagentd.socket || true
