#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with the sudo command to continue."
        exit 1
fi

systemctl enable --now sysstat-collect.service || true
systemctl enable --now sysstat-collect.timer || true
systemctl enable --now sysstat || true
systemctl enable --now sysstat-summary.service || true
systemctl enable --now sysstat-summary.timer || true
