#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable vboxweb || true
systemctl enable virtualbox || true
systemctl enable virtualbox-guest-utils || true
systemctl start virtualbox-guest-utils || true
