#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

systemctl enable open-vm-tools || true
systemctl start open-vm-tools || true
systemctl enable vgauth || true
systemctl start vgauth || true
