#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

rm -f /usr/share/applications/balena-etcher-electron.desktop || true
rm -f /usr/share/applications/bat.desktop || true
rm -f /usr/share/applications/bleachbit-root.desktop || true
rm -f /usr/share/applications/clamtk.desktop || true
rm -f /usr/share/applications/clamtk-kde.desktop || true
rm -f /usr/share/applications/clusterssh.desktop || true
rm -f /usr/share/applications/codium.desktop || true
rm -f /usr/share/applications/codium-url-handler.desktop || true
rm -f /usr/share/applications/conky.desktop || true
rm -f /usr/share/applications/debian-uxterm.desktop || true
rm -f /usr/share/applications/debian-xterm.desktop || true
rm -f /usr/share/applications/ddrescue-gui.desktop || true
rm -f /usr/share/applications/ddrescueview.desktop || true
rm -f /usr/share/applications/designer-qt5.desktop || true
rm -f /usr/share/applications/driftnet.desktop || true
rm -f /usr/share/applications/ettercap.desktop || true
rm -f /usr/share/applications/etherape.desktop || true
rm -f /usr/share/applications/filezilla.desktop || true
rm -f /usr/share/applications/firefox-esr.desktop || true
rm -f /usr/share/applications/gftp.desktop || true
rm -f /usr/share/applications/gksu.desktop || true
rm -f /usr/share/applications/gparted.desktop || true
rm -f /usr/share/applications/grdesktop.desktop || true
rm -f /usr/share/applications/grsync.desktop || true
rm -f /usr/share/applications/gsmartcontrol.desktop || true
rm -f /usr/share/applications/gtkhash.desktop || true
rm -f /usr/share/applications/guymager.desktop || true
rm -f /usr/share/applications/hardinfo.desktop || true
rm -f /usr/share/applications/htop.desktop || true
rm -f /usr/share/applications/hydra-gtk.desktop || true
rm -f /usr/share/applications/jmeter.desktop || true
rm -f /usr/share/applications/kismet.desktop || true
rm -f /usr/share/applications/lftp.desktop || true
rm -f /usr/share/applications/linguist-qt5.desktop || true
rm -f /usr/share/applications/lshw-gtk.desktop || true
rm -f /usr/share/applications/lstopo.desktop || true
rm -f /usr/share/applications/mate-disk-usage-analyzer.desktop || true
rm -f /usr/share/applications/mc.desktop || true
rm -f /usr/share/applications/mcedit.desktop || true
rm -f /usr/share/applications/mutt.desktop || true
rm -f /usr/share/applications/minicom.desktop || true
rm -f /usr/share/applications/kde4/nmapsi4-admin.desktop || true
rm -f /usr/share/applications/kde4/nmapsi4.desktop || true
rm -f /usr/share/applications/ophcrack.desktop || true
rm -f /usr/share/applications/org.bleachbit.BleachBit.desktop || true
rm -f /usr/share/applications/org.gnome.baobab.desktop || true
rm -f /usr/share/applications/org.keepassxc.KeePassXC.desktop || true
rm -f /usr/share/applications/org.remmina.Remmina.desktop || true
rm -f /usr/share/applications/packeth.desktop || true
rm -f /usr/share/applications/packetsender.desktop || true
rm -f /usr/share/applications/psensor.desktop || true
rm -f /usr/share/applications/qemu.desktop || true
rm -f /usr/share/applications/qtop.desktop || true
rm -f /usr/share/applications/R.desktop || true
rm -f /usr/share/applications/remote-viewer.desktop || true
rm -f /usr/share/applications/remmina-file.desktop || true
rm -f /usr/share/applications/remmina-gnome.desktop || true
rm -f /usr/share/applications/terminator.desktop || true
rm -f /usr/share/applications/timeshift-gtk.desktop || true
rm -f /usr/share/applications/unetbootin.desktop || true
rm -f /usr/share/applications/virt-manager.desktop || true
rm -f /usr/share/applications/virtualbox.desktop || true
rm -f /usr/share/applications/wireshark.desktop || true
rm -f /usr/share/applications/xca.desktop || true
rm -f /usr/share/applications/xsensors.desktop || true
rm -f /usr/share/applications/zulucrypt-gui.desktop || true
rm -f /usr/share/applications/zulumount-gui.desktop || true
