#!/bin/bash

set -e

RED='\e[1;31m'

if [[ "$EUID" -ne "0" ]]; then
        echo -e $RED "Run this script as root or with sudo command."
        exit 1
fi

export DEBIAN_FRONTEND=noninteractive

apt update && apt -y --fix-missing full-upgrade || true && apt -y --fix-broken install && apt -y --fix-missing full-upgrade || true && apt -y autoremove
