#!/bin/bash

set -e

YELLOW='\e[0;33m'
GREEN='\e[1;32m'

echo -e $GREEN "Welcome at Kaisen Linux NETINST configurator."
	echo ""
	echo -e $GREEN "It is a set of scripts that allows you to automate certain tasks according to your installation choices and also allows you to install software packages for Kaisen by category."
	echo ""
	echo -e $GREEN "This script will do this:"
	echo ""
	echo -e $GREEN "   1) Apply HTTPS to the repositories provided by default."
	echo -e $GREEN "   2) Will check if you are running Kaisen under VirtualBox or QEMU to install the full guests suite."
	echo -e $GREEN "   3) You will be offered to install a series of software at your convenience."
	echo -e $GREEN "   4) The services installed by the programs will be disabled at startup and stopped to save resources."
	echo -e $GREEN "   5) It will install the Linux headers (which can be useful and requested by some software)."
	echo -e $GREEN "   6) Will activate the virtualbox kernel module (if installed) at startup."
	echo -e $GREEN "   7) Removed the kaisen-netinst-configurator-launcher command as well as the execution of the script on next reboots."
	echo -e $GREEN "   8) You will be asked if you want to delete the configurator after use."
	echo ""
	echo -e $YELLOW "If you don't want to run the configurator now, you can always run it with the command \033[95msudo kaisen-netinst-configurator\e[0;33m later."
	echo ""

	while [[ $OPTION != "y" && $OPTION != "n" ]]; do
		read -rp "$(echo -e $YELLOW "Do you wish to continue? [y/n]")" OPTION;tput init
	done
	echo ""

if [[ $OPTION = "y" ]]; then
	echo -e $YELLOW "Ok, launching /usr/sbin/kaisen-netinst-configurator. You will be asked for your sudo password.";tput init
	sudo /usr/sbin/kaisen-netinst-configurator
else
	echo -e $YELLOW "Ok, remove only kaisen-netinst-configurator-launcher. You will be asked for your sudo password.";tput init
	sudo rm -f /usr/bin/kaisen-netinst-configurator-launcher
	sudo rm -f /etc/xdg/autostart/kaisen-netinst-configurator-launcher.desktop
	echo -e $GREEN "The kaisen-netinst-configurator launcher has been deleted."
fi
