#!/bin/bash

set -e

YELLOW='\e[0;33m'
GREEN='\e[1;32m'
RED='\e[1;31m'

detectvirt=$(systemd-detect-virt || true)

if [[ $EUID -ne 0 ]]; then
	echo -e $RED "Run this script as root or with the sudo command."
	exit 1
fi

https-default-repositories() {
echo -e $YELLOW "Change default repositories to HTTPS...";tput init;

sed -i 's/deb http:\/\/deb.kaisenlinux.org/deb https:\/\/deb.kaisenlinux.org/g' /etc/apt/sources.list
sed -i 's/deb-src http:\/\/deb.kaisenlinux.org/deb-src https:\/\/deb.kaisenlinux.org/g' /etc/apt/sources.list
apt update

echo -e $GREEN "Done.";tput init;
}

package-installer() {
echo -e $YELLOW "Application of tasks for installing Kaisen Linux packages and metapackages...";tput init;
mv -f /usr/share/tasksel/descs/debian-tasks.desc /usr/share/tasksel/descs/debian-tasks.desc.orig
cp -f /usr/share/kaisen-netinst-configurator/packages-list /usr/share/tasksel/descs/debian-tasks.desc

echo -e $GREEN "Launch of tasksel...";tput init;
tasksel || true

echo -e $YELLOW "Reapplication of the default tasks of tasksel...";tput init;
mv -f /usr/share/tasksel/descs/debian-tasks.desc.orig /usr/share/tasksel/descs/debian-tasks.desc
echo -e $GREEN "Done.";tput init;
}

virtualbox-guests() {
if [ $detectvirt = oracle ]; then
        echo -e $YELLOW "Kaisen is installed on VirtualBox. Install all VirtualBox guests...";tput init;
        apt install -y virtualbox-guest-dkms virtualbox-guest-source virtualbox-guest-utils virtualbox-guest-x11
fi
echo -e $GREEN "Done.";tput init;
}

qemu-guests() {
if [ $detectvirt = kvm ]; then
        echo -e $YELLOW "Kaisen is installed on QEMU. Install all QEMU guests...";tput init;
        apt install -y xserver-xorg-video-qxl qemu-guest-agent spice-vdagent spice-webdavd
fi
echo -e $GREEN "Done.";tput init;
}

disable-services() {
echo -e $YELLOW "Deactivation of additionals installed services...";tput init;
if [ -e /opt/services/all-services-disable ] && [ -x /opt/services/all-services-disable ]; then
	/opt/services/all-services-disable
else
	systemctl disable 2ping 2> /dev/null || true
	systemctl stop 2ping 2> /dev/null || true
	systemctl disable arpalert 2> /dev/null || true
	systemctl stop arpalert 2> /dev/null || true
	systemctl disable arpwatch 2> /dev/null || true
	systemctl stop arpwatch 2> /dev/null || true
	systemctl disable avahi-daemon 2> /dev/null || true
	systemctl stop avahi-daemon 2> /dev/null || true
	systemctl disable bacula-fd 2> /dev/null || true
	systemctl stop bacula-fd 2> /dev/null || true
	systemctl disable bacula-sd 2> /dev/null || true
	systemctl stop bacula-sd 2> /dev/null || true
	systemctl disable bettercap 2> /dev/null || true
	systemctl stop bettercap 2> /dev/null || true
	systemctl disable bluetooth 2> /dev/null || true
	systemctl stop bluetooth 2> /dev/null || true
	systemctl disable blueman-mechanism 2> /dev/null || true
	systemctl stop blueman-mechanism 2> /dev/null || true
	systemctl disable btrbk.timer 2> /dev/null || true
	systemctl stop btrbk.timer 2> /dev/null || true
	systemctl disable btrbk.service 2> /dev/null || true
	systemctl stop btrbk.service 2> /dev/null || true
	systemctl disable btrfs-balance.service 2> /dev/null || true
	systemctl stop btrfs-balance.service 2> /dev/null || true
	systemctl disable btrfs-balance.timer 2> /dev/null || true
	systemctl stop btrfs-balance.timer 2> /dev/null || true
	systemctl disable btrfs-defrag.service 2> /dev/null || true
	systemctl stop btrfs-defrag.service 2> /dev/null || true
	systemctl disable btrfs-defrag.timer 2> /dev/null || true
	systemctl stop btrfs-defrag.timer 2> /dev/null || true
	systemctl disable btrfsmaintenance-refresh.path 2> /dev/null || true
	systemctl stop btrfsmaintenance-refresh.path 2> /dev/null || true
	systemctl disable btrfsmaintenance-refresh.service 2> /dev/null || true
	systemctl stop btrfsmaintenance-refresh.service 2> /dev/null || true
	systemctl disable btrfs-scrub.timer 2> /dev/null || true
	systemctl stop btrfs-scrub.timer 2> /dev/null || true
	systemctl disable btrfs-scrub.service 2> /dev/null || true
	systemctl stop btrfs-scrub.service 2> /dev/null || true
	systemctl disable btrfs-trim.timer 2> /dev/null || true
	systemctl stop btrfs-trim.timer 2> /dev/null || true
	systemctl disable btrfs-trim.service 2> /dev/null || true
	systemctl stop btrfs-trim.service 2> /dev/null || true
	systemctl disable ceph-fuse.target 2> /dev/null || true
	systemctl stop ceph-fuse.target 2> /dev/null || true
	systemctl disable clamav-daemon 2> /dev/null || true
	systemctl stop clamav-daemon 2> /dev/null || true
	systemctl disable clamav-freshclam 2> /dev/null || true
	systemctl stop clamav-freshclam 2> /dev/null || true
	systemctl disable clamav-milter 2> /dev/null || true
	systemctl stop clamav-milter 2> /dev/null || true
	systemctl disable containerd 2> /dev/null || true
	systemctl stop containerd 2> /dev/null || true
	systemctl disable cups-browsed 2> /dev/null || true
	systemctl stop cups-browsed 2> /dev/null || true
	systemctl disable cups 2> /dev/null || true
	systemctl stop cups 2> /dev/null || true
	systemctl disable cups.path 2> /dev/null || true
	systemctl stop cups.path 2> /dev/null || true
	systemctl disable cups.socket 2> /dev/null || true
	systemctl stop cups.socket 2> /dev/null || true
	systemctl disable darkstat 2> /dev/null || true
	systemctl stop darkstat 2> /dev/null || true
	systemctl disable docker 2> /dev/null || true
	systemctl stop docker 2> /dev/null || true
	systemctl disable docker.socket 2> /dev/null || true
	systemctl stop docker.socket 2> /dev/null || true
	systemctl disable e2scrub_reap 2> /dev/null || true
	systemctl stop e2scrub_reap 2> /dev/null || true
	systemctl disable e2scrub_all.timer 2> /dev/null || true
	systemctl stop e2scrub_all.timer 2> /dev/null || true
	systemctl disable etc-setserial 2> /dev/null || true
	systemctl stop etc-setserial 2> /dev/null || true
	systemctl disable iptables 2> /dev/null || true
	systemctl stop iptables 2> /dev/null || true
	systemctl disable ip6tables 2> /dev/null || true
	systemctl stop ip6tables 2> /dev/null || true
	systemctl disable netfilter-persistent 2> /dev/null || true
	systemctl stop netfilter-persistent 2> /dev/null || true
	systemctl disable gns3-server 2> /dev/null || true
	systemctl stop gns3-server 2> /dev/null || true
	systemctl disable hddtemp 2> /dev/null || true
	systemctl stop hddtemp 2> /dev/null || true
	systemctl disable hostapd 2> /dev/null || true
	systemctl stop hostapd 2> /dev/null || true
	systemctl disable irqbalance 2> /dev/null || true
	systemctl stop irqbalance 2> /dev/null || true
	systemctl disable libvirtd.service 2> /dev/null || true
	systemctl stop libvirtd.service 2> /dev/null || true
	systemctl disable virtlockd.socket 2> /dev/null || true
	systemctl stop virtlockd.socket 2> /dev/null || true
	systemctl disable virtlogd.socket 2> /dev/null || true
	systemctl stop virtlogd.socket 2> /dev/null || true
	systemctl disable libvirtd.socket 2> /dev/null || true
	systemctl stop libvirtd.socket 2> /dev/null || true
	systemctl disable libvirtd-ro.socket 2> /dev/null || true
	systemctl stop libvirtd-ro.socket 2> /dev/null || true
	systemctl disable libvirt-guests.service 2> /dev/null || true
	systemctl stop libvirt-guests.service 2> /dev/null || true
	systemctl disable libvirtd-admin.socket 2> /dev/null || true
	systemctl stop libvirtd-admin.socket 2> /dev/null || true
	systemctl disable virtlockd-admin.socket 2> /dev/null || true
	systemctl stop virtlockd-admin.socket 2> /dev/null || true
	systemctl disable virtlogd-admin.socket 2> /dev/null || true
	systemctl stop virtlogd-admin.socket 2> /dev/null || true
	systemctl disable spice-vdagentd.service 2> /dev/null || true
	systemctl stop spice-vdagentd.service 2> /dev/null || true
	systemctl disable spice-vdagentd.socket 2> /dev/null || true
	systemctl stop spice-vdagentd.socket 2> /dev/null || true
	systemctl disable spice-webdavd.service 2> /dev/null || true
	systemctl stop spice-webdavd.service 2> /dev/null || true
	systemctl disable lm-sensors 2> /dev/null || true
	systemctl stop lm-sensors 2> /dev/null || true
	systemctl disable lockdown 2> /dev/null || true
	systemctl stop lockdown 2> /dev/null || true
	systemctl disable lxcfs 2> /dev/null || true
	systemctl stop lxcfs 2> /dev/null || true
	systemctl disable lxc-net 2> /dev/null || true
	systemctl stop lxc-net 2> /dev/null || true
	systemctl disable lxc 2> /dev/null || true
	systemctl stop lxc 2> /dev/null || true
	systemctl disable mlocate.timer 2> /dev/null || true
	systemctl stop mlocate.timer 2> /dev/null || true
	systemctl disable mlocate.service 2> /dev/null || true
	systemctl stop mlocate.service 2> /dev/null || true
	systemctl disable neo4j 2> /dev/null || true
	systemctl stop neo4j 2> /dev/null || true
	systemctl disable nfs-client.target 2> /dev/null || true
	systemctl stop nfs-client.target 2> /dev/null || true
	systemctl disable nfs-kernel-server 2> /dev/null || true
	systemctl stop nfs-kernel-server 2> /dev/null || true
	systemctl disable nfs-server 2> /dev/null || true
	systemctl stop nfs-server 2> /dev/null || true
	systemctl disable portmap 2> /dev/null || true
	systemctl stop portmap 2> /dev/null || true
	systemctl disable rpcbind 2> /dev/null || true
	systemctl stop rpcbind 2> /dev/null || true
	systemctl disable rpcbind.socket 2> /dev/null || true
	systemctl stop rpcbind.socket 2> /dev/null || true
	systemctl disable ntp 2> /dev/null || true
	systemctl stop ntp 2> /dev/null || true
	systemctl disable o2cb 2> /dev/null || true
	systemctl stop o2cb 2> /dev/null || true
	systemctl disable ocfs2 2> /dev/null || true
	systemctl stop ocfs2 2> /dev/null || true
	systemctl disable openvpn 2> /dev/null || true
	systemctl stop openvpn 2> /dev/null || true
	systemctl disable rpcbind 2> /dev/null || true
	systemctl stop rpcbind 2> /dev/null || true
	systemctl disable rpcbind.socket 2> /dev/null || true
	systemctl stop rpcbind.socket 2> /dev/null || true
	systemctl disable rsync 2> /dev/null || true
	systemctl stop rsync 2> /dev/null || true
	systemctl disable setserial 2> /dev/null || true
	systemctl stop setserial 2> /dev/null || true
	systemctl disable smartmontools 2> /dev/null || true
	systemctl stop smartmontools 2> /dev/null || true
	systemctl disable snapper-boot.timer 2> /dev/null || true
	systemctl stop snapper-boot.timer 2> /dev/null || true
	systemctl disable snapper-boot.service 2> /dev/null || true
	systemctl stop snapper-boot.service 2> /dev/null || true
	systemctl disable snapper-cleanup.timer 2> /dev/null || true
	systemctl stop snapper-cleanup.timer 2> /dev/null || true
	systemctl disable snapper-cleanup.service 2> /dev/null || true
	systemctl stop snapper-cleanup.service 2> /dev/null || true
	systemctl disable snapperd 2> /dev/null || true
	systemctl stop snapperd 2> /dev/null || true
	systemctl disable snapper-timeline.timer 2> /dev/null || true
	systemctl stop snapper-timeline.timer 2> /dev/null || true
	systemctl disable snapper-timeline.service 2> /dev/null || true
	systemctl stop snapper-timeline.service 2> /dev/null || true
	systemctl disable ssh 2> /dev/null || true
	systemctl stop ssh 2> /dev/null || true
	systemctl disable sysstat 2> /dev/null || true
	systemctl stop sysstat 2> /dev/null || true
	systemctl disable vboxweb 2> /dev/null || true
	systemctl stop vboxweb 2> /dev/null || true
	systemctl disable virtualbox 2> /dev/null || true
	systemctl stop virtualbox 2> /dev/null || true
	systemctl disable virtualbox-guest-utils 2> /dev/null || true
	systemctl stop virtualbox-guest-utils 2> /dev/null || true
	systemctl disable vgauth 2> /dev/null || true
	systemctl stop vgauth 2> /dev/null || true
	systemctl disable open-vm-tools 2> /dev/null || true
	systemctl stop open-vm-tools 2> /dev/null || true
	systemctl disable zfs-fuse 2> /dev/null || true
	systemctl stop zfs-fuse 2> /dev/null || true
fi
echo -e $GREEN "Done.";tput init;
}

install-kernel-headers() {
echo -e $YELLOW "Install kernel headers...";tput init;
apt install -y linux-headers-$(uname -r)
echo -e $GREEN "Done.";tput init;
}

virtualbox-autoload-module() {
if [ -e /usr/lib/modules/[0-9]*.[0-9]*.[0-9]*-kaisen[0-9]*-amd64/updates/vboxdrv.ko ] && [ -e /var/lib/dkms/virtualbox/[0-9]*.[0-9]*.[0-9]*/[0-9]*.[0-9]*.[0-9]*-kaisen[0-9]*-amd64/x86_64/module/vboxdrv.ko ]; then
	echo -e $YELLOW "Auto load VirtualBox module at boot";tput init;
	echo "vboxdrv" > /etc/modules-load.d/virtualbox.conf
	echo -e $GREEN "The vboxdrv module has been added for launch at boot.";tput init;
fi
}

remove-launcher() {
if [ -e /etc/xdg/autostart/kaisen-netinst-configurator.desktop ] && [ -e /usr/bin/kaisen-netinst-configurator-launcher ]; then
	rm -f /etc/xdg/autostart/kaisen-netinst-configurator.desktop
	rm -f /usr/bin/kaisen-netinst-configurator-launcher
fi
}

remove-configurator() {
while [[ $OPTION != "y" && $OPTION != "n" ]]; do
	read -rp "$(echo -e $YELLOW "Would you like to delete the configurator? [y/n]")" OPTION;tput init;
done
echo ""

if [[ $OPTION = "y" ]]; then
	echo -e $YELLOW "Removing the configurator...";tput init;
	apt remove --purge -y kaisen-netinst-configurator
	echo -e $GREEN "The configurator has been deleted.";tput init;
else
	echo -e $GREEN "Ok, the configurator is always installed.";tput init;
fi
}

https-default-repositories
package-installer
virtualbox-guests
qemu-guests
disable-services
install-kernel-headers
virtualbox-autoload-module
remove-launcher
remove-configurator
